### ISSUE TITLE
Signed PID for for_pid?

### ISSUE THREAD

**Issue by jbreitbart** [gz/rust-perfcnt#17]
The function `perfcnt::linux::PerfCounterBuilderLinux::for_pid()` expects a PID as a parameter, but the type is defined as i32. Is this done intentionally? `std::process::id` returns a u32.

Here is a link to the documentation: http://gz.github.io/rust-perfcnt/perfcnt/linux/struct.PerfCounterBuilderLinux.html#method.for_pid

**Comment by gz** [comment]
Hm, I may have modeled it after libc https://docs.rs/libc/0.2.69/libc/type.pid_t.html which takes an i32. Unfortunate that they are not the same. It also looks like for_all_pids() uses `-1` to avoid being a process specific counter. Not that it would matter we might as well use `u32::MAX`. Do you know why libc and std arrived at different types for the pid?

**Comment by jbreitbart** [comment]
I didn't realize the libc crate uses i32, but I guess it makes sense. At least for glibc `pid_t` is defined as an int. [0] `std::process::id` uses u32 as Windows uses a 32bit unsigned value for its process ID. [1]

[0] https://www.gnu.org/software/libc/manual/html_node/Process-Identification.html
[1] https://github.com/rust-lang/rust/commit/1ec7a697328fb10e7135b87557ff0a5ea702dd8d

**Comment by gz** [comment]
Thanks for checking. I guess it makes sense here to keep it consistent with the linux/unix pid_t definition, even though it's a bit of a nuisance to convert. Thoughts?

**Comment by jbreitbart** [comment]
I agree, it's certainly not worth breaking the existing API. Feel free to just close the issue. One alternative could be to use a generic function[0]. I can send you a PR if you want one, or just do the conversion in my code. Let me know. Anyhow, thanks for the crate. :smile: 

[0] https://play.rust-lang.org/?version=nightly&mode=debug&edition=2015&gist=8e9e88a185db1cba47ec5056a833829e

**Comment by gz** [comment]
Thanks, yes the fail on conversion is kind of bad so ideally we can avoid it by keeping proper types in the API definitions. Let me close for now. I'm glad the crate is of use to you.
