### ISSUE TITLE
Any interest in supporting Apple M1/M2?

### ISSUE THREAD

**Issue by marshallpierce** [gz/rust-perfcnt#28]
I just came across https://lemire.me/blog/2023/03/21/counting-cycles-and-instructions-on-arm-based-apple-systems/, which shows that there is a way to access counters on macOS M1/M2. Would this potentially be in scope for this crate, or would you prefer to keep this x86 specific?

**Comment by gz** [comment]
Hi right now this is pretty Linux/x86 specific yes, but I'm happy to review changes that also makes this more widely available on other platforms so if this is something that you'd like to see in the crate we can def. do that.

**Comment by marshallpierce** [comment]
Sounds good. When I have a need for macOS counters I'll write the PR. Feel free to close this if you like; my question is answered.
